"""init

Revision ID: 3fc0a8b9bb02
Revises: 
Create Date: 2019-08-18 08:31:57.568041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.engine.reflection import Inspector

revision = '3fc0a8b9bb02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connect = op.get_bind()
    tables = Inspector.from_engine(connect).get_table_names()

    if 'serial' not in tables:
        op.create_table(
            'serial',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=150), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    if 'series' not in tables:
        op.create_table(
            'series',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('id_serial', sa.Integer(), nullable=True),
            sa.Column('series_number', sa.Integer(), nullable=True),
            sa.Column('season_number', sa.Integer(), nullable=True),
            sa.Column('looked', sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(['id_serial'], ['serial.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    op.drop_table('serial')
    # ### end Alembic commands ###
